import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Slider } from '@/src/components';
import { Box, Container, } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Toons</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box sx={{ mt: 1, mb: 1 }}>
          <Slider />
        </Box>
        <Container maxWidth="lg">Content</Container>
    </>
  );
}
